# Generated by Django 4.0.1 on 2024-04-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=234, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(upload_to='files/about_us/', verbose_name='Видео')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=123, verbose_name='Полное имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=123, verbose_name='Номер телефона')),
                ('comment', models.TextField(blank=True, default='Пусто', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/features/', verbose_name='Изображение')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/catalog/', verbose_name='Изображение')),
                ('image_bg', models.ImageField(upload_to='images/catalog_no_bg/', verbose_name='Изображение на фон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог игр',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/home/')),
            ],
            options={
                'verbose_name': 'Дом изображении',
                'verbose_name_plural': 'Дом изображении',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='images/homepage/')),
                ('image2', models.ImageField(upload_to='images/homepage/')),
                ('image3', models.ImageField(upload_to='images/homepage/')),
                ('image4', models.ImageField(upload_to='images/homepage/')),
                ('image5', models.ImageField(upload_to='images/homepage/')),
                ('image6', models.ImageField(upload_to='images/homepage/')),
                ('image7', models.ImageField(upload_to='images/homepage/')),
                ('image8', models.ImageField(upload_to='images/homepage/')),
                ('text_for_email', models.TextField(verbose_name='Описание для писем отправки')),
                ('meta_image', models.FileField(upload_to='images/meta/')),
                ('site_name', models.CharField(help_text='The name of the website', max_length=255, verbose_name='Название сайта')),
                ('logo', models.FileField(blank=True, help_text='The logo of the website', null=True, upload_to='logos/', verbose_name='Logo')),
                ('footer_logo', models.FileField(blank=True, null=True, upload_to='logos/', verbose_name='Footer Logo')),
                ('favicon', models.FileField(blank=True, help_text='The favicon of the website', null=True, upload_to='favicons/', verbose_name='Favicon')),
                ('default_meta_description', models.TextField(help_text='Default meta description for SEO', max_length=20000, verbose_name='Default Meta Description')),
                ('default_meta_keywords', models.CharField(help_text='Default meta keywords for SEO', max_length=255, verbose_name='Default Meta Keywords')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/news/%Y/%m/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=123, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/review/%Y/%m/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='files/reviews/', verbose_name='Видео')),
                ('created_at', models.DateTimeField(verbose_name='Дата создание')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='Оригинальный текст, который отображается на сайте.', max_length=20000, verbose_name='Оригинальный текст')),
                ('current_text', models.TextField(help_text='Измененный или текущий текст, который отображается на сайте.', max_length=20000, verbose_name='Текущий текст')),
            ],
            options={
                'verbose_name': 'Контент сайта',
                'verbose_name_plural': 'Контент сайта',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=123, verbose_name='Адрес')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Инстраграм')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Телеграмм')),
                ('whatsup', models.URLField(blank=True, null=True, verbose_name='Вотсап')),
                ('vk', models.URLField(blank=True, null=True, verbose_name='Вк')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Ютуб')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Фейсбук')),
                ('address_link', models.URLField(verbose_name='Ссылка на адрес')),
                ('address_iframe', models.TextField(verbose_name='iframe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('phones', models.ManyToManyField(to='game.Phone', verbose_name='Номера')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
